// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awlhbbprlwzmbimubcvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bGhiYnBybHd6bWJpbXViY3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMDE0MzIsImV4cCI6MjA3NzY3NzQzMn0.sMvKq8G_RO_a4bmR_Na31GVS0ZxO1VqN63qUqfBvsKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});